[Quality control] Mainly Out control form
rudnickirobert/KWZP2019 pull request #105
Opened 2019-05-03 21:33 UTC by kingak123

2019-05-04 07:40 UTC, rudnickirobert requested changes

2019-05-04 07:40 UTC, rudnickirobert commented on KWZP2019/KWZP2019/OutControlForm.cs
> +                txtbAcceptableWidthDeviation.Text = null;
i co w związku z tym? cos wiecej ma sie wydarzyc? czy tylko pokazemy userowi puste inputy?

2019-05-04 07:40 UTC, rudnickirobert commented on KWZP2019/KWZP2019/OutControlForm.cs
> +                    case "W takcie realizacji":
trakcie

2019-05-04 10:12 UTC, kingak123 commented on KWZP2019/KWZP2019/OutControlForm.cs
> +                txtbAcceptableWidthDeviation.Text = null;
wartości txtb.Text zmieniają się dynamicznie w zależność od wybranego numeru procesu, w tym przypadku czyści pola po wcześniej wybranym dla przypadku nowych pomiarów, dodatkowo umożliwia ich edytowanie ( już poza elsem, korzystając z wartości boola przekazywanego do metody)

2019-05-04 17:50 UTC, rudnickirobert commented on KWZP2019/KWZP2019/OutControlForm.cs
> +                txtbAcceptableWidthDeviation.Text = null;
czuje sie przekonany :)

2019-05-04 17:51 UTC, rudnickirobert commented
@kingak123 konflikty

2019-05-04 19:13 UTC, kingak123 commented
Konflikty rozwiązane, sql bez errorów, aplikacja kompiluje się i działa :)

2019-05-04 19:19 UTC, kingak123 commented on KWZP2019/KWZP2019/OutControlForm.cs
> +                    case "W takcie realizacji":
poprawione

2019-05-05 07:49 UTC, rudnickirobert requested changes
nadal konflikty

2019-05-06 20:10 UTC, kingak123 commented
Konflikty ponownie rozwiązane.

2019-05-07 05:53 UTC, rudnickirobert submitted a review, later dismissed

2019-05-07 19:21 UTC, kingak123 commented
Konflikty ponownie rozwiązane........

2019-05-07 20:46 UTC, rudnickirobert approved these changes

2019-05-07 20:46 UTC, merged