[Production] add remove process employee
rudnickirobert/KWZP2019 pull request #107
Opened 2019-05-04 15:50 UTC by michalmolski

2019-05-04 17:54 UTC, rudnickirobert requested changes

2019-05-04 17:54 UTC, rudnickirobert commented on KWZP2019/KWZP2019/AddNewCustomerForm.cs
> +                    newCustomer.PhoneNumber = Convert.ToString(phoneTb21);
dlaczego nie `phoneTb21.Text`?

2019-05-04 17:54 UTC, rudnickirobert commented on KWZP2019/KWZP2019/AddNewCustomerForm.cs
> +                    newCustomer.PhoneNumber = Convert.ToString(phoneTb21);
i co oznacza te `21`?

2019-05-05 15:20 UTC, DamianSzupienko commented
Proszę nie mergować brancha ze względu na znaczne błędy w modelu EF, jest do zamknięcia

2019-05-05 15:20 UTC, closed without merging