[Maintenance Managment] Updated Parts Managment & Entity Data Model
rudnickirobert/KWZP2019 pull request #108
Opened 2019-05-04 18:54 UTC by pposs

**Zaktualizowano formularz PartsForm** - utworzono dataGridView dla cześci oraz dodano opcje wyszukiwania, dodawania, usuwania, edycji części

**Utworzono formularz PartsRequest** - utworzono dataGridView dla zapotrzebowań na cześci oraz dodano opcję wyszukiwania (po dacie i nazwie części), dodawania (formularz PartsRequest_Add), usuwania, akceptacji zapotrzebowania, a także historię zapotrzebowań na części

**Zaktualizowano RoofingCompany.sql** - dodano widok zapotrzebowania na części i edytowano widoki części

**Zaktualizowano Entity Data Model** - dodano vPartsRequestView, poprawiono vPartsView & vMaintPartsView

2019-05-05 07:56 UTC, rudnickirobert requested changes

2019-05-05 07:56 UTC, rudnickirobert commented on KWZP2019/KWZP2019/PartsForm.cs
> +        private bool hided;
`hidden`

2019-05-05 07:56 UTC, rudnickirobert commented on KWZP2019/KWZP2019/PartsForm.cs
> +        private bool updatepanel;
camelCase

2019-05-05 07:56 UTC, rudnickirobert commented on KWZP2019/KWZP2019/PartsForm.cs
> +        private bool hided;
warto tez dopisac w zmiennej co jest ukryte bo samo hidden wskazuje na caly formularz

2019-05-05 07:56 UTC, rudnickirobert commented on KWZP2019/KWZP2019/PartsForm.cs
> +            }
bo `MessageBox.Show` dodac `return` i wtedy `else` niepotrzebny i mamy jedno wciecie mniej :)

2019-05-05 07:56 UTC, rudnickirobert commented on RoofingCompany.sql
> +SELECT TOP 100 PERCENT Part.PartName,
`TOP 100 PERCENT` niedopuszczalne

2019-05-05 07:56 UTC, rudnickirobert commented on RoofingCompany.sql
> +SELECT TOP 100 PERCENT Maintenance.MaintenanceNr, Maintenance.DateAcceptOrder,
jw

2019-05-05 12:26 UTC, pposs commented
**Formularz PartsForm i plik RoofingCompany.sql zostały zaktualizowane** - poprawiono wymienione błędy

**Rozwiązano konflikty z aktualną wersją na masterze**

2019-05-06 11:29 UTC, pposs commented
**Zaktualizowano do obecnej wersji na masterze (ostatnie działanie - zmergowanie pull request #110) w celu wykluczenia konfliktów**

2019-05-07 05:54 UTC, rudnickirobert approved these changes

2019-05-07 05:54 UTC, rudnickirobert requested changes

2019-05-07 05:54 UTC, rudnickirobert commented on RoofingCompany.sql
> +SELECT TOP 100 PERCENT Part.PartName,
nadal do usuniecia

2019-05-07 09:08 UTC, pposs commented
**Zaktualizowano do obecnej wersji na masterze (ostatnie działanie - zmergowanie pull request #116).

Poprawiono błędy w RoofingCompany.sql.

Rozwiązano konflikty.**

2019-05-07 17:24 UTC, rudnickirobert approved these changes

2019-05-07 17:25 UTC, merged