Okienka dla Finansów i HR
rudnickirobert/KWZP2019 pull request #11
Opened 2019-04-08 16:20 UTC by MichalBrr

2019-04-09 17:29 UTC, rudnickirobert requested changes

2019-04-09 17:29 UTC, rudnickirobert commented on KWZP2019/FinanseiHR/WindowsFormsApp1/WindowsFormsApp1.sln
> +﻿
co to za plik? mamy już plik .`sln` w projekcie

2019-04-09 17:29 UTC, rudnickirobert commented on KWZP2019/FinanseiHR/WindowsFormsApp1/WindowsFormsApp1/Absences.cs
> +namespace WindowsFormsApp1
zły namespace, pozwolę sobie w tym miejscu przerwać przeglądanie kodu- wygląda na doklejony drugi projekt

2019-04-15 13:55 UTC, rudnickirobert requested changes
pozostaje do poprawy

2019-04-15 14:05 UTC, mkujda commented
Resolved in (https://github.com/rudnickirobert/KWZP2019/pull/16/files). Closing

2019-04-15 14:05 UTC, closed without merging