[Maintenance Management] Add and modyfing forms, add views
rudnickirobert/KWZP2019 pull request #121
Opened 2019-05-07 13:25 UTC by pawelkosno

… views

2019-05-07 17:39 UTC, rudnickirobert requested changes

2019-05-07 17:39 UTC, rudnickirobert commented on KWZP2019/KWZP2019/MaintenanceEmployeeCalendarForm.cs
> +        private void PopulateDataGridView()
nazwa metody z małej litery

2019-05-07 17:39 UTC, rudnickirobert commented on KWZP2019/KWZP2019/MachinesForm.cs
> +                PopulateDataGridView();
nazwa metody z małej litery

2019-05-07 19:00 UTC, pawelkosno commented
Rozwiązano konflikty

2019-05-07 20:54 UTC, rudnickirobert submitted a review, later dismissed

2019-05-07 22:15 UTC, pposs commented
**Naprawiono Entity Data Model.**

**Rozwiązano konflikty z aktualną wersją na masterze  (ostatnie działanie - zmergowanie pull request #128)**

2019-05-08 05:42 UTC, rudnickirobert submitted a review, later dismissed

2019-05-08 06:45 UTC, pawelkosno commented
Rozwiązano konflikty

2019-05-08 07:01 UTC, closed without merging