Dodano wszytkie okienka
rudnickirobert/KWZP2019 pull request #24
Opened 2019-04-15 16:05 UTC by KubaBartkiewicz

2019-04-15 16:08 UTC, rudnickirobert requested changes

2019-04-15 16:08 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Addfvat.cs
> +        public Addfvat()
camelCase, nie używamy skrótów tylko pełnych nazw

2019-04-15 16:08 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Addfvat.cs
> +    public partial class Addfvat : Form
camelCase, nie używamy skrótów tylko pełnych nazw

2019-04-15 16:08 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Allcosts.cs
> +    public partial class Allcosts : Form
camelCase

2019-04-15 16:08 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Finances.cs
> +            Salaries obecnosci = new Salaries();
angielskie nazwy zmiennych

2019-04-15 16:08 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Finances.cs
> +            Salariessummary urlopy = new Salariessummary();
camelCase

2019-04-15 16:08 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Salariessummary.cs
> +    public partial class Salariessummary : Form
camelCase

2019-04-15 16:08 UTC, rudnickirobert commented on KWZP2019/KWZP2019/KWZP2019.csproj
> +  <ItemGroup />
potrzebne?

2019-04-15 16:27 UTC, KubaBartkiewicz commented
poprawione

2019-04-15 19:52 UTC, rudnickirobert requested changes

2019-04-15 19:52 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Finances.cs
> +            Salariessummary salariessummary = new Salariessummary();
camelCase...

2019-04-15 19:52 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Finances.cs
> +            Allcosts allcosts = new Allcosts();
jw

2019-04-15 19:52 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Addfvat.cs
> +    public partial class AddInovoice : Form
literówka

2019-04-15 19:52 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/Finances.cs
> +            AddInvoices addinvoices = new Addfvat();
jw

2019-04-16 17:51 UTC, rudnickirobert approved these changes

2019-04-16 17:52 UTC, merged