[HRFinanse] Praca nad GUI
rudnickirobert/KWZP2019 pull request #40
Opened 2019-04-17 16:12 UTC by annakowalczyk1

2019-04-17 16:27 UTC, rudnickirobert submitted a review, later dismissed

2019-04-17 21:04 UTC, mkujda commented
Master posiada błędy, proszę nie mergować. Konflikty zostaną rozwiązane na działającym masterze.

2019-04-18 12:41 UTC, mkujda commented
Resolved conflicts with #42.

2019-04-18 14:07 UTC, rudnickirobert requested changes

2019-04-18 14:07 UTC, rudnickirobert commented on KWZP2019/KWZP2019/OshTrainingForm.cs
> +            foreach(Department dep in departmentList)
`foreach(Department department in departmentList)`
nie ma potrzeby skracać nazw

2019-04-24 16:08 UTC, closed without merging