[Quality Control] Entrance control form c# code finished
rudnickirobert/KWZP2019 pull request #46
Opened 2019-04-18 10:53 UTC by Bartelix

2019-04-18 13:57 UTC, rudnickirobert requested changes

2019-04-18 13:57 UTC, rudnickirobert commented on KWZP2019/KWZP2019/KWZP2019.csproj
> +    <Compile Include="EntranceControlView1.cs">
skąd ta `1`? nie powinno jej  być w nazwie encji

2019-04-18 14:22 UTC, Bartelix commented on KWZP2019/KWZP2019/KWZP2019.csproj
> +    <Compile Include="EntranceControlView1.cs">
usunięte

2019-04-18 14:35 UTC, rudnickirobert requested changes

2019-04-18 14:35 UTC, rudnickirobert commented on KWZP2019/KWZP2019/KWZP2019.csproj
> +    <Compile Include="vCustomerWithOrder1.cs">
tu też `1`

2019-04-18 14:35 UTC, rudnickirobert commented on KWZP2019/KWZP2019/RoofingCompanyModel.edmx.diagram
> +        <EntityTypeShape EntityType="RoofingCompanyModel.vCustomerWithOrder1" Width="1.5" PointX="9.375" PointY="22.75" />
tu zostały 1

2019-04-18 15:29 UTC, Bartelix commented on KWZP2019/KWZP2019/KWZP2019.csproj
> +    <Compile Include="vCustomerWithOrder1.cs">
poprawione

2019-04-24 08:06 UTC, Bartelix commented
Konflikty rozwiązane, wszystko działa, proszę o merge'a

2019-04-24 17:23 UTC, rudnickirobert approved these changes

2019-04-24 17:44 UTC, merged