[HR Finances] A lot of changes
rudnickirobert/KWZP2019 pull request #73
Opened 2019-04-29 14:36 UTC by mkujda

Its not a bug, its a feature.

Graphics, Forms.

2019-04-29 14:49 UTC, rudnickirobert requested changes

2019-04-29 14:49 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/PaymentHistory.cs
> +        SqlConnection sqlConnection = new SqlConnection("server =.\\SQLEXPRESS;Database=RoofingCompany;Integrated Security=true");
mamy to w zmiennej `db`

2019-04-29 14:49 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Finances/PaymentHistory.cs
> +            ("SELECT dbo.Employee.EmployeeName, dbo.Employee.EmployeeSurname, dbo.Employee.PESEL, " +
to może do widoku?

2019-05-05 07:35 UTC, rudnickirobert commented
@mkujda co z tym PR?

2019-05-06 17:03 UTC, mkujda commented
@rudnickirobert za Pana pozwoleniem zamknę, wszystkie zmiany zawarte tutaj znajdowały się w branchu który był wszedł na mastera.

2019-05-07 05:47 UTC, rudnickirobert commented
@mkujda gdyby tak było to nie byłoby ani konfliktów ani zmian pokazanych przez githuba :)
ale na zamknięcie mogę się zgodzić- wtedy zauważy Pan czego brakuje

2019-05-07 11:25 UTC, closed without merging