[QualityControl] DevelopmentFormGUI
rudnickirobert/KWZP2019 pull request #85
Opened 2019-04-30 16:26 UTC by YupiKayey

[QualityControl] Dodanie GUI do formularza DevelopmentForm

2019-05-01 10:16 UTC, rudnickirobert requested changes
konflikty

2019-05-04 07:26 UTC, rudnickirobert commented
nadal konflikty

2019-05-06 06:29 UTC, rudnickirobert requested changes
doskonały przykład tego, że nie powinno się dodawac nowego kodu do istniejacego PRa

2019-05-06 06:29 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentForm.cs
> +        private byte[] newPatternImage = null;
niepotrzebne `=null`

2019-05-06 06:29 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentForm.cs
> +                FEMAnalysi fEMAnalysi = new FEMAnalysi();
powinno byc `FEMAnalysis`

2019-05-06 06:29 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentForm.cs
> +                FEMAnalysi fEMAnalysi = new FEMAnalysi();
zarowno w nazwie klasy jak i zmiennej

2019-05-06 06:29 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentHistoryForm.cs
> +            List<FEMAnalysi> fEMAnalysis = db.FEMAnalysis.ToList();
nazwa zmiennej powinna wskazywac na to ze jest to kolekcja a nie pojedynczy obiekt

2019-05-06 06:29 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentHistoryForm.cs
> +            //lblEmployeeFullName.Text = $"{employee.EmployeeName} {employee.EmployeeSurname}";
zakomentowany kod...

2019-05-06 10:06 UTC, PatrykBanach95 commented
Proszę o nie łączenie z gałęzią główną z racji niepoprawnie rozwiązanego konfliktu

2019-05-07 05:49 UTC, rudnickirobert requested changes

2019-05-07 05:49 UTC, rudnickirobert commented on RoofingCompanyInserts.sql
> +/*insert into FEMAnalysis (IdEmployee, NewPattern, AnalysisResults, AnalysisDate) values
znów zakomentowany kod...

2019-05-07 05:49 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentForm.cs
> +            if (textBoxDescription.Text == "" || textBoxEmployeeId.Text == "" || dateTimePicker.Text == "" |newPatternImage == null )
czemu jeden pipe?

2019-05-07 05:50 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentForm.cs
> +                FEMAnalysi fEMAnalysi = new FEMAnalysi();
@YupiKayey nadal nie naprawione

2019-05-07 08:41 UTC, PatrykBanach95 commented
niepoprawnie rozwiązany konflikt

2019-05-07 17:00 UTC, rudnickirobert requested changes

2019-05-07 17:00 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentForm.cs
> +                    Employee Employee = db.Employees.First(emp => emp.IdEmployee.ToString() == textBoxEmployeeId.Text);
dlaczego? nazwa zmiennej powinna była zostać pisana z małej litery

2019-05-07 17:00 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentHistoryForm.cs
> +            FEMAnalysi FEMAnalysi = db.FEMAnalysis.First(fEMA => fEMA.IdFEMAnalysis.ToString() == domainUpDownDevelompentNumber.Text);
jw- powinno było zostać z małej litery

2019-05-07 17:13 UTC, rudnickirobert commented on KWZP2019/KWZP2019/DevelopmentHistoryForm.cs
> +            List<FEMAnalysi> fEMAnalysis = db.FEMAnalysis.ToList();
@YupiKayey w komentarzu https://github.com/rudnickirobert/KWZP2019/pull/85#discussion_r281071383
chodziło o literkę `s` na końcu- nadal nie poprawione

2019-05-07 17:14 UTC, rudnickirobert requested changes
prośba o poprawę

2019-05-07 17:40 UTC, rudnickirobert approved these changes

2019-05-07 17:40 UTC, merged