[HANDLOWY] New View EmployeeSalesDepartment
rudnickirobert/KWZP2019 pull request #86
Opened 2019-04-30 23:02 UTC by AdriannaArtych

2019-05-01 10:17 UTC, rudnickirobert requested changes

2019-05-01 10:17 UTC, rudnickirobert commented on RoofingCompany.sql
> +/*
nie commitujemy zakomentowanego kodu- jeśli tworzenie widoku powoduje błędy w wykonaniu skryptu należy go naprawić (https://deviq.com/boy-scout-rule/)
... albo usunąć

2019-05-03 12:26 UTC, rudnickirobert commented
konflikty

2019-05-04 07:28 UTC, rudnickirobert requested changes
konflikty

2019-05-04 07:43 UTC, AdriannaArtych commented
usunięty konflikt

2019-05-04 07:54 UTC, rudnickirobert approved these changes

2019-05-04 07:54 UTC, merged