Added NewProductionFailure_form
rudnickirobert/KWZP2019 pull request #88
Opened 2019-05-01 15:22 UTC by mateusz1kazana

Added_NewProductionFailure_ form

2019-05-01 16:18 UTC, rudnickirobert requested changes

2019-05-01 16:18 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Production/NewProductionFailure.cs
> +            if (idFailure > 0)
co jeśli `idFailure  <1' ? co ma się wtedy stać?

2019-05-01 16:18 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Production/NewProductionFailure.cs
> +            if (failure != null)
tutaj failure nigdy nie będzie `null`- w poprzedniej linijce stał się obiektem typu `Failure`

2019-05-01 16:18 UTC, rudnickirobert commented on KWZP2019/KWZP2019/Production/NewProductionFailure.cs
> +                MessageBox.Show("Wprowadź wszystkie dane");
zatem to nigdy się nie wykona

2019-05-01 16:18 UTC, rudnickirobert commented on RoofingCompany.sql
> +SELECT TOP 10 PERCENT Part.PartName as [Nazwa części],
10 procent? poproszę bardzo silny argument :)

2019-05-04 07:30 UTC, rudnickirobert requested changes
konflikty 
+ proszę odpowiedziec: https://github.com/rudnickirobert/KWZP2019/pull/88#discussion_r280124157

2019-05-04 10:35 UTC, mateusz1kazana commented on RoofingCompany.sql
> +SELECT TOP 10 PERCENT Part.PartName as [Nazwa części],
Dodałem dla sprawdzenia działania po czy zapomniałem usunąć

2019-05-04 17:45 UTC, rudnickirobert requested changes
w takim razie proszę usunąc

2019-05-04 17:45 UTC, rudnickirobert commented on RoofingCompany.sql
> +SELECT TOP 10 PERCENT Part.PartName as [Nazwa części],
w takim razie proszę usunąc

2019-05-05 07:38 UTC, rudnickirobert approved these changes

2019-05-05 07:38 UTC, merged