[Maintenance Managment] Updated Parts Form & Entity Data Model
rudnickirobert/KWZP2019 pull request #93
Opened 2019-05-02 01:40 UTC by pposs

**Zaktualizowano formularz części** - utworzono DataGridView dla części oraz opcje wyszukiwania, dodawania, usuwania i edytowania danych części

**Zaktualizowano Entity Data Model** - dodano nowe widoki i poprawiono drobne błędy

2019-05-03 12:33 UTC, rudnickirobert requested changes
konflikty

2019-05-03 18:20 UTC, pposs commented
**Rozwiązano istniejące konflikty.**

2019-05-04 07:32 UTC, rudnickirobert commented
nadal konflikty

2019-05-04 18:12 UTC, closed without merging

2019-05-04 18:25 UTC, rudnickirobert commented
@pposs czemu zamkniety?

2019-05-04 19:02 UTC, pposs commented
Brak kompatybilności z aktualną wersją na masterze - wiele konfliktów.

Utworzyłem nowego brancha w oparciu o aktualną wersję na masterze i wprowadziłem swoje zmiany.